version: "3.4"
services: 
    app:
        build : .
        container_name: node1-container
        env_file: .env
        ports: 
            - "3001:3000"
        networks: 
            - server
        depends_on: 
            - db
    db:
        image: mongo
        container_name: mongo
        networks: 
            - server
networks: 
    server:
        driver: bridge